FROM bitnami/python:3.10.15

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY nlp_server.py /app/nlp_server.py

EXPOSE 8080

CMD uvicorn 'nlp_server:app' --host=0.0.0.0 --port=8080